services:
  postgres:
    image: postgres:14
    networks:
      - local
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: henefisa
      POSTGRES_DB: school
      POSTGRES_DATA: /var/lib/postgresql/data
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data
networks:
  local:
    driver: bridge
volumes:
  db:
